<?php

$ACCOUNT_ID = $_REQUEST['ACCOUNT_ID'];
$USERNAME = $_REQUEST['USERNAME'];
$PASSWORD = $_REQUEST['PASSWORD'];
$md5PASSWORD = md5($PASSWORD);

$SSN = $_REQUEST['SSN'];
$NAME = $_REQUEST['NAME'];
$SURNAME = $_REQUEST['SURNAME'];
$JOB_ID = $_REQUEST['JOB_ID'];
$SALARY = $_REQUEST['SALARY'];
$START_CONTRACT = $_REQUEST['START_CONTRACT'];
$END_CONTRACT = $_REQUEST['END_CONTRACT'];

require '../../../connect_oracle.php';

$s = oci_parse($c, "insert into HOSPITAL_STAFFS(ACCOUNT_ID,USERNAME,PASSWORD,SSN,NAME,SURNAME,JOB_ID,SALARY,START_CONTRACT,END_CONTRACT) 
					values('$ACCOUNT_ID','$USERNAME','$md5PASSWORD','$SSN','$NAME','$SURNAME','$JOB_ID','$SALARY',TO_DATE('$START_CONTRACT','MM/DD/YYYY'),TO_DATE('$END_CONTRACT','MM/DD/YYYY'))");
$r = oci_execute($s);

echo json_encode(array(
	'ACCOUNT_ID' => $ACCOUNT_ID,
	'USERNAME' => $USERNAME,
	'PASSWORD' => $md5PASSWORD,
	'SSN' => $SSN,
	'NAME' => $NAME,
	'SURNAME' => $SURNAME,
	'JOB_ID' => $JOB_ID,
	'SALARY' => $SALARY,
	'START_CONTRACT' => $START_CONTRACT,
	'END_CONTRACT' => $END_CONTRACT
	
));

?>